### ISSUE TITLE
Support syntastic

### ISSUE THREAD

**Issue by Kuniwak** [Kuniwak/vint#13]
Example: https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/vim/vimlint.vim

**Comment by todesking** [comment]
作ってみました https://github.com/todesking/vimfiles/blob/master/syntax_checkers/vim/vint.vim

**Comment by todesking** [comment]
有効にするには `let g:syntastic_vim_checkers = ['vint']` する必要あり

**Comment by Kuniwak** [comment]
ありがとうございます！！！！！！！ :clap::clap::clap::clap::clap::clap:

できればパッケージマネージャーで読み込めるようにリポジトリで管理したほうがよいと思うので、リポジトリについて相談させてください。
実は前にチャレンジして失敗して放置していた[の](https://github.com/Kuniwak/vint-syntastic/blob/master/syntax_checkers/vim/vint.vim)もあるのですが、今回すべて @todesking さんが書かれたものなので、todesking さんのリポジトリにするのが妥当だと思っています。いかがでしょうか。

**Comment by todesking** [comment]
あっ既に存在していたのですか……
ちなみにそちらのだとどんな問題ありました?

**Comment by Kuniwak** [comment]
いえ、恥ずかしながら動かなかったのです。

**Comment by todesking** [comment]
つくりました https://github.com/todesking/vint-syntastic

**Comment by Kuniwak** [comment]
:+1::+1::+1::+1::+1:

**Comment by Kuniwak** [comment]
README にのっけたら close します！

**Comment by Kuniwak** [comment]
done: #114
