### ISSUE TITLE
Neovim mode?

### ISSUE THREAD

**Issue by blueyed** [Kuniwak/vint#130]
I am getting the following error from my vimrc:

    E492: Not an editor command: tnoremap <C-h> <C-\><C-n><C-w>h (see ynkdir/vim-vimlparser)

It is used like this:

    if exists(':tnoremap')  " Neovim
      tnoremap <C-h> <C-\><C-n><C-w>h
      tnoremap <C-j> <C-\><C-n><C-w>j
      tnoremap <C-k> <C-\><C-n><C-w>k
      tnoremap <C-l> <C-\><C-n><C-w>l
    endif

It would be useful probably to have a Neovim-mode, which needs to be supported by https://github.com/ynkdir/vim-vimlparser then probably?!

**Comment by Kuniwak** [comment]
>  then probably?!

Sounds good!
We can support it when vim-vimlparser can parse `:tnoremap`.

**Comment by zchee** [comment]
+1
#yapcasia :)

**Comment by vito-c** [comment]
+1

**Comment by RianFuro** [comment]
I opened a pull request over there with changes to support the neovim command set. ynkdir/vim-vimlparser#19

If that goes through all that's left is to make a command line switch for neovim support in vint that's passed into the parser :)

**Comment by Kuniwak** [comment]
Thank you, @RianFuro !

This feature was shipped with v0.3.6.
Please update and try it.
