### ISSUE TITLE
Please unbundle vimlparser

### ISSUE THREAD

**Issue by Coacher** [Kuniwak/vint#134]
Hello.

Currently vimlparser is imported unconditionally from extlib/. Please provide a way to use system-wide installation of vimlparser if one is available. try..except with ImportError should do the trick the same way it is done in compat/.

**Comment by Kuniwak** [comment]
Sorry for my late reply.

I have a question.
Why do you want to use system-wide installation of vimlparser?

**Comment by Coacher** [comment]
Because I wish to properly package vint for my distro. And that extlib is getting installed directly to site-packages/ dir, because it is not under vint/ dir. Same for compat/, test/, and dev_tool/, but I can avoid installing them, while extlib/ is a requirement for the normal vint functioning.

This is a bigger problem with `find_packages()` in setup.py and your project structure. `find_packages()` without arguments grabs all packages in the tree and with your project layout not all vint related packages are under vint/ dir.

`setuptools` docs suggest using find_packages() for packages with a certain structure. See examples from docs: https://github.com/twisted/twisted and http://svn.eby-sarna.com/PEAK/

The problem with installing vint related files not under vint/ dir is not only a possibility for file collisions, but also leads to problems during import, when several packages install files under say test/ dir in site-packages or extlib/.

**Comment by Kuniwak** [comment]
OK.
Could you send a PullRequest about this problem?

**Comment by Coacher** [comment]
Which one?

Unbundling vimlparser (or hiding it under vint/ dir) is a trivial fix. Properly fixing your project layout is not so trivial and will require a whole bunch of import fixes most probably.

**Comment by Kuniwak** [comment]
I feel the last one is better.
And the first one is also enough.

You can choose the one that you like.
I'll leave it up to you.
