### ISSUE TITLE
Feature request: Suppress specific warnings/errors?

### ISSUE THREAD

**Issue by tyru** [Kuniwak/vint#151]
I want a way to suppress specific warnings/errors like [vim-vimlint](https://github.com/syngan/vim-vimlint).

```viml
" @vimlint(EVL103, 1, a:node)
function s:VimlLint.compile_delfunction(node, refchk) " {{{
  .....
endfunction " }}}
" @vimlint(EVL103, 0, a:node)
```

(code from http://d.hatena.ne.jp/syngan/20140321/1395411106)

**Comment by rhysd** [comment]
@tyru 

Are you looking for [comment-config](https://github.com/Kuniwak/vint#comment-config)?

**Comment by tyru** [comment]
That's it! thanks!
