### ISSUE TITLE
request neovim support

### ISSUE THREAD

**Issue by wsdjeg** [Kuniwak/vint#153]
E492: Not an editor command: tnoremap <C-Right> <C-\><C-n><C-w><Right> (see ynkdir/vim-vimlparser)

`tmap` is the command for neovim

**Comment by Kuniwak** [comment]
This issue is duplicated (#130)

**Comment by wsdjeg** [comment]
thanks ,now I am using neomake,but I find it does not work,
I using `pip install --user vim-vint` install this proj;
and the vint is in `~/.local/bin` which is not in my PATH by default,
