### ISSUE TITLE
Severity level and default config

### ISSUE THREAD

**Issue by RianFuro** [Kuniwak/vint#154]
I tried out vint and ran it with --error from the command line, without having any config file defined whatsoever. Still, I got a bunch of style_problem errors printed, namely from the ProhibitImplicitScopeVariable policy.

Dug into the code and found out it's because it's set as an enabled policy in the default config file, so it's ignoring the severity level I set.
I see it's designed like that so explicitly set policies take priority over the severity level, but wouldn't it make sense for the default configuration to adhere to any explicit settings I make? It seems counter intuitive to have style_problem level messages when all I defined was an error-only severity level.

**Comment by Kuniwak** [comment]
Thanks.

It is fixed on v0.3.5.
Please update vint.

**Comment by RianFuro** [comment]
Wicked fast! Thanks :)
