### ISSUE TITLE
Use ~= for requirements

### ISSUE THREAD

**Issue by sils1297** [Kuniwak/vint#162]
Hey, you seem to use == for requirements, this may lead to version conflicts. ~= let's you allow all API compatible versions and thus your programm is way less likely to error out especially when used in a env with other programs. (And we all know that not all users do use an own env for every program.)

**Comment by underyx** [comment]
:+1: with the new pyyaml 3.12 release this issue just broke everything that uses pyyaml and vim-vint, including [coala](https://github.com/coala-analyzer/coala).
