### ISSUE TITLE
Please provide a --no-color command line argument

### ISSUE THREAD

**Issue by blueyed** [Kuniwak/vint#167]
That would be useful for e.g. Neomake to disable the `color` setting from a user's config (Ref: https://github.com/neomake/neomake/issues/442).

Alternatively, it would be nice to use colors automatically, e.g. by detecting if stdin is connected etc.

**Comment by Kuniwak** [comment]
Hi, the [`--no-color` option](https://github.com/Kuniwak/vint/wiki/Config#color-settings) is now available.
Please update Vint and try it.

**Comment by blueyed** [comment]
Awesome, thanks a lot!
From looking at the code I believe that it works.

**Comment by blueyed** [comment]
Works, thanks!
