### ISSUE TITLE
I'd like vint to support .yml as well as .yaml

### ISSUE THREAD

**Issue by ryunix** [Kuniwak/vint#171]
`.vintrc.yaml`固定となっていますが、`.vintrc.yml`も対応してほしいです。

理由としては、他のYAMLファイルとの統一性やそもそもの好み(拡張子は3文字が好き)という点があります。

**Comment by Kuniwak** [comment]
This feature was release as [v0.3.9](https://pypi.python.org/pypi/vim-vint/0.3.9).

Please upgrade Vint and try it.

**Comment by ryunix** [comment]
`.vintrc.yml`での動作を確認しました。
対応ありがとうございます。
