### ISSUE TITLE
Error 404 to the google style guide in wiki

### ISSUE THREAD

**Issue by Sathors** [Kuniwak/vint#176]
The links to the google vimscript style guide give error 404 in the wiki page.

Thanks for the great work!

**Comment by Kuniwak** [comment]
Thanks for reporting.

I fixed the broken links ([diff](https://github.com/Kuniwak/vint/wiki/Vint-linting-policy-summary/_compare/3d577037cf189d9ac6bb79c617169e0e032d23cc...e9119be8e997f8b38476d8c0066c47b8cb0faedc)).

**Comment by Sathors** [comment]
Thanks @Kuniwak !
