### ISSUE TITLE
Policy `ProhibitImplicitScopeBuiltinVariable` is not defined

### ISSUE THREAD

**Issue by prashcr** [Kuniwak/vint#185]
I tried using this policy from https://github.com/Kuniwak/vint/wiki/Vint-linting-policy-summary, but it seems to be undefined.

**Comment by w0rp** [comment]
I think you just need to use the `-s` option for this.

**Comment by prashcr** [comment]
Thanks!

**Comment by Alok** [comment]
I used the `-s` flag and got the same error. I'm using `vint` version `0.3.10`.`
