### ISSUE TITLE
ConfigProjectSource might use ConfigGlobalSource

### ISSUE THREAD

**Issue by blueyed** [Kuniwak/vint#194]
Given `/home/user/project/.vintrc.yaml` and `/home/user/.vintrc.yaml`, `ConfigProjectSource` will first find the project config, but then also the user's global config, which it then uses instead.

I think a sensible fix for this is to stop once the first config has been found.

Also, ignoring the global config explicitly might make sense.
Vint could stop at the user's home directory to address this?!

Also, `ConfigGlobalSource` should look at `~/.config/vint/config` (`$XDG_CONFIG_HOME/yamllint/config`) first, which would work around this.

**Comment by Kuniwak** [comment]
I shipped this bugfix on v0.3.11.
