### ISSUE TITLE
ProhibitEqualTildeOperator: be smarter about cases where it is not required

### ISSUE THREAD

**Issue by blueyed** [Kuniwak/vint#195]
It would be nice if the `ProhibitEqualTildeOperator` ("Use robust operators `==#` or `==?` instead of `==`") policy would ignore cases/violations when there is no ambiguity, e.g. when comparing numbers (as string), spaces (`line !~ '^  '`) or with the empty string (`if foo == ''`).

I don't mind using it always myself, but I can see that maintainers/people do not like it.

What do you think?
The case for empty strings could be handled rather easily probably, and otherwise we could check if the upper-case version of all chars is the same as the lower-case version?!

**Comment by Kuniwak** [comment]
Make sense.

Why I implement `ProhibitEqualTildeOperator` is to avoid risk caused by the problematic operators.
And `foo == ''` have no risk.
