### ISSUE TITLE
Typo in policy rule name

### ISSUE THREAD

**Issue by lcd047** [Kuniwak/vint#199]
The name of the policy rule `ProhibitImplicitScopeBuiltinVariable` is actually [implemented](https://github.com/Kuniwak/vint/blob/master/vint/linting/policy/prohibit_implicit_scope_builtin_variable.py#L12-L14) as `ProhibitImplicitScopeBuitlinVariable` (`t` and `l` in `Builtin` are swapped).  Consequently, enabling `ProhibitImplicitScopeBuiltinVariable` in `.vintrc.yaml` has no effect, the misspelled has to be used instead. :smile:

**Comment by Kuniwak** [comment]
Thanks for reporting.

Would you PullRequest that resolve this?

**Comment by lcd047** [comment]
Done in #200.
