### ISSUE TITLE
Old version of enum34

### ISSUE THREAD

**Issue by lafrenierejm** [Kuniwak/vint#203]
Is there a reason why enum34 is set to version 1.0.4 exactly as opposed to 1.0.4 or newer?

**Comment by Kuniwak** [comment]
I think that there are no reason.

Hi @lambdalisue, I want to hear your opinion. What do you think it?

**Comment by lafrenierejm** [comment]
I can confirm that the python2 version works with enum34 1.1.6.

**Comment by lambdalisue** [comment]
Yes. There is no particular reason to stick that version.

**Comment by Kuniwak** [comment]
Hi, @lafrenierejm, would you send a pull request to fix this problem?
