### ISSUE TITLE
:packadd and :packloadall should be permitted

### ISSUE THREAD

**Issue by nelstrom** [Kuniwak/vint#210]
Vim 8 added [support for packages](http://vimhelp.appspot.com/repeat.txt.html#packages), with these new commands:

* [`:packadd`](http://vimhelp.appspot.com/repeat.txt.html#%3Apackadd)
* [`:packloadall`](http://vimhelp.appspot.com/repeat.txt.html#%3Apackl)

Currently, vint reports `E492: Not an editor command` if either of these commands appear in a script.

**Comment by blueyed** [comment]
Fixed in a477d9d.
