### ISSUE TITLE
Allow autocmd User

### ISSUE THREAD

**Issue by uplus** [Kuniwak/vint#212]
下記のようにautocmdでUserを使うとエラー扱いされます。

```vim
au User MyEvent echo 'Hello'
```

エラーメッセージ

```text
autocmd should execute in an augroup or execute with a group (see :help :autocmd)
```

**Comment by Kuniwak** [comment]
@uplus この警告は、autocmd がグループ付きでなく、かつ augroup で囲まれていない時に出るものです。提示いただいたコードは augroup に囲まれているのかどうか確認をお願いいたします。

**Comment by uplus** [comment]
augroupに囲まれていませんでした。
どうやらUserをグループと勘違いしていたようです。
ありがとうございました!
