### ISSUE TITLE
vim-vint is incompatible with requests 2.16.2

### ISSUE THREAD

**Issue by jayvdb** [Kuniwak/vint#216]
requests 2.16.2 has been released with a mandatory requirement on chardet >= 3.0.2, < 3.1.0.

`vim-vint` requires `chardet ~= 2.3.0` , which means it isnt possible to use it and `requests` in the same package, otherwise `pkg_resources` will raise `VersionConflict`.

You can see this occurring at https://circleci.com/gh/jayvdb/coala/298

**Comment by Kuniwak** [comment]
I shipped the fixed version. Please check it.
https://pypi.python.org/pypi/vim-vint/0.3.12

**Comment by jayvdb** [comment]
Thanks so much ; we are doing a rebuild to check, then will close this if all is green again and we can go back to pretending that we can safely rely on external python packages.

**Comment by jayvdb** [comment]
All good.
