### ISSUE TITLE
Tests fail if vint is not installed

### ISSUE THREAD

**Issue by Coacher** [Kuniwak/vint#223]
Hello.

test/acceptance/test_cli.py calls `vint` with args. When vint isn't installed there is no `vint` command in PATH, so tests fail. Also relying on the installed `vint` executable defies testing purposes as already installed version is tested, not the current one.

Solution: explicitly call `bin/vint`. Fix: `sed -i -e "s|'vint'|'bin/vint'|g" test/acceptance/test_cli{,_vital}.py`

**Comment by Coacher** [comment]
@Kuniwak, need PR? Really? The sed line with fix is in the OP...

**Comment by blueyed** [comment]
Fixed in 8c34196.
