### ISSUE TITLE
`tno` not recognized - 'Not an editor command'

### ISSUE THREAD

**Issue by lwm** [Kuniwak/vint#229]
I see: `Not an editor command: tno <C-h> <C-\><C-n><C-w>h (SyntaxError)`

**Comment by blueyed** [comment]
You need `--enable-neovim`.
See https://github.com/Kuniwak/vint/issues/130.

**Comment by blueyed** [comment]
btw: Neomake adds this automatically: https://github.com/neomake/neomake/blob/a5881d9bae9e344f32d5df02a0290a7671be846f/autoload/neomake/makers/ft/vim.vim#L11-L13

**Comment by lwm** [comment]
Thanks!
