### ISSUE TITLE
substitute() is not :substitute

### ISSUE THREAD

**Issue by sedm0784** [Kuniwak/vint#241]
When I use the `substitute()` function, I get the following two warnings:

> Do not use a command that has unintended side effects (see Google VimScript Style Guide (Dangerous))
> Avoid commands that rely on user settings (see Google VimScript Style Guide (Fragile))

However, both cited sections of the Google Vimscript Style Guide caution against using the `:substitute` *command* which is a different thing altogether.

**Comment by blueyed** [comment]
How do you trigger it?

The following does not cause a warning for me:

> call substitute('foo', 'bar', 'baz', '')

**Comment by sedm0784** [comment]
Sorry, I should've written a proper test case for you when I created this issue.

I can't reproduce it, either, now.
