### ISSUE TITLE
ProhibitImplicitScopeVariable is not an anitpattern

### ISSUE THREAD

**Issue by still-dreaming-1** [Kuniwak/vint#245]
In my opinion, and probably in most people's opinion, this should not be considered an antipattern or be enabled by default. Most plugin authors prefer to use implicit scope, at least for local variables inside functions. When scope is specified everywhere, the code inside functions becomes less readable. It also trains the reader to ignore the scope, thereby not noticing when a special scope is used.

Even inside one's main config file, it would be strange and unnecessary to specify global scope for every variable you set outside of a function.

The default scope rules when you don't specify the scope are very appropriate, global when outside a function, and local when inside a function.

**Comment by Kuniwak** [comment]
The reason why I implement the rule is a variable name conflict such as `count`.
In Vim script, `count` is implicitly becomes to `v:count`.

But, I think that this problem can be resolved by detecting built-in variable name conflicts.
So, we can change the severity of ProhibitImplicitScopeVariale to Style Problem, and create a new policy such as ProhibitBuiltinVariableNameConflict.

And if most users is disabling ProhibitImplicitScopeVariable, I'm gonna change the default settings of ProhibitImplicitScopeVariable.

How do you feel it?

**Comment by still-dreaming-1** [comment]
That would be great! It is good to know more details about why this is considered an antipattern. I tried looking up the references, but it didn't give any specific examples of problems this fixes, so I really appreciate this example. If you are able to detect built in variable name conflicts, and do that instead of prohibiting implicit scope all the time, that would be perfect.

**Comment by tjdevries** [comment]
I don't think that'd be terribly difficult to do. Here's the result from `sort(keys(v:))`.

```
_null_dict
_null_list
beval_bufnr
beval_col
beval_lnum
beval_text
beval_winid
beval_winnr
char
charconvert_from
charconvert_to
cmdarg
cmdbang
command_output
completed_item
count
count1
ctype
dying
errmsg
errors
event
exception
exiting
false
fcs_choice
fcs_reason
fname
fname_diff
fname_in
fname_new
fname_out
folddashes
foldend
foldlevel
foldstart
hlsearch
insertmode
lang
lc_time
lnum
mouse_col
mouse_lnum
mouse_win
mouse_winid
msgpack_types
null
oldfiles
operator
option_new
option_old
option_type
prevcount
profiling
progname
progpath
register
scrollstart
searchforward
servername
shell_error
statusmsg
swapchoice
swapcommand
swapname
t_bool
t_dict
t_float
t_func
t_list
t_number
t_string
termresponse
testing
this_session
throwpoint
true
version
vim_did_enter
warningmsg
windowid
```

**Comment by tyru** [comment]
not all above variables implicitly become to v:var.
seeing Vim's source code, the only below variables (variables with `VV_COMPAT` flag in `vimvars` table in eval.c):

* count
* errmsg
* shell_error
* this_session
* version

**Comment by still-dreaming-1** [comment]
Seems like Vim itself should be changed to follow more consistent rules. It should never implicitly change a variable to the `v:` scope.

**Comment by tyru** [comment]
I don't know much about the history of Vim though, `VV_COMPAT` seems compatible flag, and recent added built-in variables doesn't do such weird behavior.

**Comment by still-dreaming-1** [comment]
If it is just a few variables that work that way for backward compatibility reasons, linting for just those variables is a reasonable approach.

**Comment by tjdevries** [comment]
I think using just `true` in a function should give a linting error. It should be `v:true` almost 100% of the time I think.

It seems reasonable to warn people they are potentially using vim-only variables.

**Comment by tyru** [comment]
@tjdevries hmm, I often use some variables such like `lnum`, expecting `l:lnum` not `v:lnum`.
IMHO, I *expect*, basically, variable without scope (e.g. `v:`, `l:`) behave like local-scope variable not vim-only variable. and some variables like `count` and `errmsg` are exceptional patterns. so they should be checked as built-in variable name conflicts (now I found that `ProhibitImplicitScopeBuiltinVariable` does this, is this enabled by default? >@Kuniwak ).

But I can understand what you (@tjdevries) say and expect.
If it is useful, I think it might as well be implemented as a new linting policy (not default).

**Comment by tyru** [comment]
https://github.com/Kuniwak/vint/wiki/Vint-linting-policy-summary

@Kuniwak above page does not says about enabled/disabled by default. I think currently all policies are enabled by default. is this right?

**Comment by still-dreaming-1** [comment]
@tyru I tested it and it is enabled by default. I had to explicitly turn it off to disable the warning when using `count` variable inside a function. So it seems we already have what we want just by disabling `ProhibitImplicitScopeVariable` since `ProhibitImplicitScopeBuiltinVariable` is a thing and is already enabled.

**Comment by tyru** [comment]
sorry for many questions at once.

@Kuniwak You say

> So, we can change the severity of ProhibitImplicitScopeVariale to Style Problem, and create a new policy such as ProhibitBuiltinVariableNameConflict.

But it seems `ProhibitBuiltinVariableNameConflict` is already implemented as `ProhibitImplicitScopeBuiltinVariable` if I'm not wrong.
Are these two policies identical?

**Comment by Kuniwak** [comment]
@tyru Oops, you're right. And the severity of ProhibitImplicitScopeVariable is already Style Problem...

Now, I read [the reference of the policy](http://rbtnn.hateblo.jp/entry/2014/12/28/010913) again.

**Comment by Kuniwak** [comment]
Maybe we should warn only implicit global variables. 🤔

**Comment by still-dreaming-1** [comment]
@Kuniwak if you want multiple flexibility, you could split it into 2 separate policies. But if you only want to have policies that are on by default, warning for implicit global variables seems good. I think most of the time, global variables are used for global variables or something similar to that. I think it is good to explicitly think about and declare the scope of every variable outside of a function.

**Comment by still-dreaming-1** [comment]
I would say as far as function local variables go, there should be a policy warning when you unnecessarily explicitly declare the scope to be local.

**Comment by blueyed** [comment]
I think we should be fine with https://github.com/Kuniwak/vint/pull/273 then.
I'm getting a warning when using `count` in a function:

> Make the scope explicit like `v:count` (or possibly be unexpected builtin?) (ProhibitImplicitScopeBuiltinVariable)

There are some more things here to consider/discuss, but not using ProhibitImplicitScopeBuiltinVariable by default is a good first step IMHO.
