### ISSUE TITLE
Get PosixPath NotImplementedError in Windows

### ISSUE THREAD

**Issue by jadero** [Kuniwak/vint#290]
Error originates from linting/cli.py. Using PurePosixPath instead seems to fix this.

**Comment by blueyed** [comment]
Please consider creating a PR, and also check with master first.

**Comment by blueyed** [comment]
This was reported for Neomake in https://github.com/neomake/neomake/issues/2172.
It appears to be fixed in 4.0a1 apparently - try `pip install --pre vim-vint`.

Hopefully there will be a release shortly.

**Comment by jayvdb** [comment]
The local reference to PosixPath was removed in 3a2729eb , which is only released as part of pre-release v0.4a1 , so 0.3.x is still effected.  Code is https://github.com/Kuniwak/vint/blob/stable-0.3/vint/linting/cli.py#L129

Note I am happy to wait, as I dont use Windows - I was just a little confused when it didnt appear to be fixed  in the latest release for the coala CI.

**Comment by blueyed** [comment]
@jayvdb 
Thanks for the reference.
The 0.3.x releases were only to fix critical things.
We should really have 0.4 sometime soon, until then I recommend to use master.
