### ISSUE TITLE
Setup guide for users

### ISSUE THREAD

**Issue by Cbhihe** [Kuniwak/vint#291]
Trouble in paradise....  to install `vint` as a syntax checker for `vim` scripts. 
 I (like so many) use `syntastic` and the `vundle`  plugin manager. 
I have trouble installing `vint` as a linter despite having done that for a little over half a dozen times for other syntax checkers. 
- I cloned  https://github.com/Kuniwak/vint in my `~/.vimrc/bundle`.
- I placed `Plugin 'Kuniwak/vint'` between `call vundle#begin()` and `call vundle#end()` in my `~/.vimrc`.
- Also in `~/.vimrc`,  I inserted: 
```
let g:syntastic_vim_checkers = ["vint"]
let g:no_vim_maps = 0
```
Last I opened a vim buffer by issuing from CLI;
```
$ vim
:PluginInstall
:PluginClean
```
No error reported here, and I traced the `vint.vim` file at location
`~/.vim/bundle/syntastic/syntax_checkers/vim/vint.vim`

At this point there is still no syntax checker at work at all after restarting vim and even the host. Maybe  specifying an executable path as :
`let g:syntastic_vim_vint_exec = "/path/to/executable"`  but which one ?
No, rather ***install*** the _executable_ with `sudo pip install vim-vint`... 

The fact that it is python had escaped me, and in retrospect, yes it is in the `readme` file, but let's say that it is not particularly salient in it, in particular because coming from other linter installations, some may require or not executables,  already or not present among installed packages.

So .... the reason I address you guys here, is not to troubleshoot user (me) issues.  It is that I believe yr user base would benefit extraordinarily from a condensed, but complete 10 lines in the _Installation_ section of your `readme`, to describe exactly how the install of `vint` as a lint checker in Syntastic goes, either natively for vim 8.x or through `vundle` or both, in a *nix type environment.

Cheers for `vint`. I like it so far.

**Comment by blueyed** [comment]
Just for info: on Arch Linux you can install python-vint from the AUR.  And as you figured out you do not have to add it to your vimrc etc, but only make the `vint` executable available.
btw: Neomake also supports vint out of the box, and is async (in contrast to Syntastic).

**Comment by Cbhihe** [comment]
Thanks much Daniel, that too would deserve a line in the readme or perhaps in an installation faq....
