### ISSUE TITLE
Release 0.3.20

### ISSUE THREAD

**Issue by blueyed** [Kuniwak/vint#299]
I've created a branch, planning to release 0.3.20: https://github.com/Kuniwak/vint/tree/stable-0.3

It is forked from v0.3.19, and only contains the fix to use `yaml.safe_load` for now.

**Comment by jayvdb** [comment]
c.f. https://github.com/Kuniwak/vint/issues/300 , a packaging enhancement so RPMs can be built from the pypi release.

**Comment by blueyed** [comment]
Released, mainly to fix issue(s) with pyyaml.
Sorry for not including #300, but it was tedious enough already.. :/

**Comment by blueyed** [comment]
@Kuniwak 
I would appreciate it if you could delete https://pypi.org/project/vim-vint/0.3.20/#history (released 0.3.21 afterwards).  While I can upload, I cannot delete releases apparently.
