### ISSUE TITLE
Support for [new] .. string concatenation operator introduced in vim 8.1.1114

### ISSUE THREAD

**Issue by systemmonkey42** [Kuniwak/vint#306]
patch 8.1.1114: confusing overloaded operator "." for string concatenation

Problem:    Confusing overloaded operator "." for string concatenation.
Solution:   Add ".." for string concatenation.  Also "let a ..= b".

Vint currently doesnt understand '`..`' as a string concatenation operator.

**Comment by blueyed** [comment]
Thanks for the report.
Needs to go into vimlparser first I guess: https://github.com/vim-jp/vim-vimlparser/issues/95
