### ISSUE TITLE
vint: next-line syntax is broken

### ISSUE THREAD

**Issue by natebosch** [Kuniwak/vint#329]
If I add a line:

```viml
" vint: next-line -ProhibitAutocmdWithNoGroup
```

I get warnings (more than one for some reason)

```
vint WARNING: Policy `line` is not defined
vint WARNING: Policy `line` is not defined
vint WARNING: Policy `line` is not defined
vint WARNING: Policy `line` is not defined
vint WARNING: Policy `line` is not defined
vint WARNING: Policy `line` is not defined
vint WARNING: Policy `line` is not defined
```

I based this comment on the example in the readme.

I'm on version `0.3.21` installed with `pip`

**Comment by blueyed** [comment]
It does not work in 0.3.21, but only later (added in https://github.com/Kuniwak/vint/commit/efff450ae8c88935af05d2fb0a4373df52eb48d4 apparently).
I recommend using master.

**Comment by openjck** [comment]
I ran into this issue as well. Thanks for reporting it, @natebosch.

@blueyed, do you think there's any way you could do a new release which includes this fix? It's pretty old to still be causing issues on the latest release.

**Comment by LRitzdorf** [comment]
The version of vint installed via `pip` (from the Python Package Index) does not include this fix. For that reason, I would suggest that this issue be reopened until the PyPI version is updated. Thanks!

**Comment by infinitewhileloop** [comment]
Uninstalling the default `pip` version (`pip uninstall vim-vint`) and then installing the latest commit `pip install git+https://github.com/Vimjas/vint.git` indeed solved this bug.

**Comment by alerque** [comment]
Six years later and this is still not in a tagged release. Can we please...?
